=== inf24tig35/inf24tig35/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="recursos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="recurso" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titulo" type="xs:string"/>
              <xs:element name="tipo" type="xs:string"/>
              <xs:element name="link" type="xs:anyURI"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== inf24tig35/inf24tig35/conteudos.xml
<?xml version="1.0" encoding="UTF-8"?>
<recursos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="schema.xsd">
  <recurso>
    <titulo>🧪 Matemática - Problemas Interativos</titulo>
    <tipo>Exercícios Interativos</tipo>
    <link>https://matematicadivertida.com</link>
  </recurso>
  <recurso>
    <titulo>🎥 Matemática - Vídeo Aula de Álgebra</titulo>
    <tipo>Vídeo</tipo>
    <link>https://www.youtube.com/watch?v=LTx-Jd7pyZ8</link>
  </recurso>
  <recurso>
    <titulo>🧪 Português - Gramática Essencial</titulo>
    <tipo>Website</tipo>
    <link>https://www.ispsn.org/sites/default/files/documentos-virtuais/pdf/gramatica_essencial_-_celso_cunha.pdf</link>
  </recurso>
  <recurso>
    <titulo>📄 Português - Compreensão de Leitura</titulo>
    <tipo>Artigo</tipo>
    <link>https://area.dge.mec.pt/gramatica/ensino_leitura_compreensao_textos.pdf</link>
  </recurso>
  <recurso>
    <titulo>🧪 Física e Química - Simulações de Experiências</titulo>
    <tipo>Simulador</tipo>
    <link>https://phet.colorado.edu/pt/</link>
  </recurso>
  <recurso>
    <titulo>🎥 Física e Química - Aula sobre Estados da Matéria</titulo>
    <tipo>Vídeo</tipo>
    <link>https://www.youtube.com/watch?v=KTOi7DMtoG8</link>
  </recurso>
  <recurso>
    <titulo>📄 Biologia - Ecossistemas</titulo>
    <tipo>Artigo</tipo>
    <link>https://www.biologianet.com/ecologia/ecossistema.htm</link>
  </recurso>
  <recurso>
    <titulo>🧪 Biologia - Genética Interativa</titulo>
    <tipo>Exercícios Interativos</tipo>
    <link>https://www.interativaguaxupe.com.br/site/wp-content/uploads/2020/03/LISTA-DE-EXERCÍCIOS-GENETICA-I-3-ANO-INTERATIVA-2020.pdf</link>
  </recurso>
  <recurso>
    <titulo>🎥 História - Revolução Francesa</titulo>
    <tipo>Vídeo</tipo>
    <link>https://www.youtube.com/watch?v=l53BJ26RXnw</link>
  </recurso>
  <recurso>
    <titulo>🧪 História - Linha do Tempo Interativa</titulo>
    <tipo>Website</tipo>
    <link>https://mundoeducacao.uol.com.br/historiageral/divisao-da-historia.htm</link>
  </recurso>
  <recurso>
    <titulo>📄 Geografia - Mapas e Territórios</titulo>
    <tipo>Artigo</tipo>
    <link>https://www.dgterritorio.gov.pt/cartografia</link>
  </recurso>
  <recurso>
    <titulo>🎥 Geografia - Climas do Mundo</titulo>
    <tipo>Vídeo</tipo>
    <link>https://www.youtube.com/watch?v=D3YQ6zl3-2M</link>
  </recurso>
  <recurso>
    <titulo>🎥 Inglês - Listening Skills</titulo>
    <tipo>Vídeo</tipo>
    <link>https://www.youtube.com/watch?v=Bx9xde8SsUs</link>
  </recurso>
  <recurso>
    <titulo>🧪 Inglês - vocabulário interativo </titulo>
    <tipo>Exercícios Interativos</tipo>
    <link>https://cursodeingles.online</link>
  </recurso>
  <recurso>
    <titulo>🧪 Educação Visual - Ferramentas Criativas</titulo>
    <tipo>Simulador</tipo>
    <link>https://www.canva.com/pt_pt/desenho/</link>
  </recurso>
  <recurso>
    <titulo>🧪 Educação Visual - Galeria de Inspiração</titulo>
    <tipo>Website</tipo>
    <link>https://pt.pinterest.com/josejoaoaragao/educacao-visual/</link>
  </recurso>
</recursos>
